# Read data

```{r}
df <-
  "C:/Users/chanb/Box Sync/Facebook pilot - Statisticians/Lifetime ad performance by ad-day 6.8.17.csv" %>% 
  read.csv(stringsAsFactors = FALSE) %>% 
  filter(Ad != "All")
oldnames <- names(df)
newnames <- c("date",
              "ad",
              "reach",
              "cost",
              "impressions",
              "cpm",
              "linkClicks",
              "ctr",
              "cpc",
              "uniqueLinkClicks",
              "uniqueCTR",
              "costPerUniqueLinkClick",
              "clicksAll",
              "ctrAll",
              "cpcAll",
              "uniqueClicksAll",
              "uniqueCTRAll",
              "costPerUniqueClickAll",
              "reactions",
              "comments",
              "shares")
names(df) <- newnames
df <-
  df %>% 
  filter(!grepl("EMP", ad)) %>% 
  mutate(date = as.Date(date, format = "%m/%d/%y")) %>% 
  mutate(image = factor(gsub("\\s-.*", "", ad)),
         text = factor(gsub(".*-\\s", "", ad))) %>% 
  mutate(text = gsub("Social norms", "SocialNorms", text)) %>% 
  mutate(text = factor(text)) %>% 
  mutate(image = relevel(image, ref = "Computer"),
         text = relevel(text, ref = "Incentive"))
```

Column name mapping.

```{r}
data.frame(old = c(oldnames, NA, NA), new = names(df)) %>% kable
```

Summarize.

```{r}
df %>% 
  group_by(image, text) %>% 
  summarize(nDays = length(date), minDate = min(date), maxDate = max(date)) %>% 
  kable
```
